// Bombs common
#define ZEUS_COMMON_DIALOG_BOMB_TIME_ID 66001
#define ZEUS_COMMON_DIALOG_SHOULD_BEEP_ID 66002
#define ZEUS_COMMON_DIALOG_EXPLOSION_CLASS_ID 66003
#define ZEUS_COMMON_DIALOG_EXPLOSION_OVERRIDE_EXPLOSION_ID 66004
#define ZEUS_COMMON_DIALOG_SERIAL_NUMBER_ID 66005
#define ZEUS_COMMON_DIALOG_MAX_DEFUSE_ATTEMPTS_ID 66006
#define ZEUS_COMMON_DIALOG_REMOVE_SHOT_VULNERABILITY_AFTER_DEFUSE_ID 66007

// Shot/Explosion Vulnerable objects common
#define ZEUS_COMMON_DIALOG_DELETE_OBJECT_AFTER_EXPLOSION_ID 66005

// Vulnerable objects
#define ZEUS_VULNERABLE_OBJECTS_GLOBAL_DIALOG_CLASS_NAMES_ID 66101 

// Wire bomb
#define ZEUS_WIRE_BOMB_DIALOG_ID 66211
#define ZEUS_WIRE_BOMB_DIALOG_WIRE_SIGN_ID 66214
#define ZEUS_WIRE_BOMB_DIALOG_WIRE_COUNT_SLIDER_ID 66215
#define ZEUS_WIRE_BOMB_DIALOG_WIRE_COUNT_ID 66220

// Keypad bomb
#define ZEUS_KEYPAD_BOMB_DIALOG_ID 66311
#define ZEUS_KEYPAD_BOMB_DIALOG_SOLUTION_CODE_ID 66314
#define ZEUS_KEYPAD_BOMB_DIALOG_GUI_TYPE_ID 66316

// Memory bomb
#define ZEUS_MEMORY_BOMB_DIALOG_ID 66411
#define ZEUS_MEMORY_BOMB_DIALOG_ROUNDS_COUNT_ID 66414

// Morse bomb
#define ZEUS_MORSE_BOMB_DIALOG_ID 66511
#define ZEUS_MORSE_BOMB_DIALOG_ENCODED_MESSAGE_ID 66512
#define ZEUS_MORSE_BOMB_DIALOG_SOLUTION_MESSAGE_ID 66513
