name = "N-Bombs"
prefix = "nbs"
mainprefix = "z"

[properties]
author = "Nerdi (Aquerr)"
url = "https://github.com/Aquerr/N-Bombs"

[version]
path = "addons/main/script_version.hpp"
git_hash = 8

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "n_bombs_logo.paa"
]
exclude = [
    ".idea/**"
]

[lints.sqf]
command_case = true
