// GUI ids
#define CLASSIC_KEYPAD_BOMB_INTERFACE_ID 67001
#define CLASSIC_KEYPAD_BOMB_INTERFACE_BACK_PANEL_ID 67002
#define KEYPAD_BOMB_INTERFACE_ID 67011
#define KEYPAD_BOMB_INTERFACE_BACK_PANEL_ID 67012

// GUI display fields
#define BOMB_GUI_ENTERED_CODE_FIELD_ID 67100
#define BOMB_GUI_SERIAL_NUMBER_FIELD_ID 67101
#define BOMB_GUI_TIME_LABEL_ID 67102